language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lucidsushi
  password:
    secure: N/3dUMVUIunJe0j8I+I2NLxvAJL4aBUCgwOqjObYkZMEsjCFoT/OZDZmfn2IP54+1lk8tr5EbdRS8rZn66De31AJRjUJbKVHAz099pZsqhile3J8C5qyIpmzi5ot1Zad6a8q5uwHLvW6JwsgpD//xC2Y3M2C5tdxx6QwxTqW3JWJzBlZDmURFpIRSUelSmJMI5/5rFjKyESjfT2O3CCio3aNcPgcSVCkl71Ba471AZIUB+0g0jxrRcs06xiYRhulnvUV+4A3thg+ozIlv5SbJGGawNPmR5AkrjGTW+IPQn1iWcCOFZmbBu7iJWXpqgR4oHxHztZEeZGgMh665UzjUuSW6ZMDgcfZgcVkz2oXOIq4J3qI/Uycm9BwBfWHAam1axF9YCddq5NlnZIdJap58f0LOX5FivNAYqSkPwcKpvHHqt0Xxsjod6HGPFo62a+hndTHGHG2VuJMQ4RFjoaxXV0LUiA4D7WyVulUHVmugeJY4GsSvxSyUonvV9dEcfUOBPJGmrROd1AK+GguiYwdxn4nnIGxXB2FjReC8w2h06WxCjIscloiC4cqQaj+eEW51Et7kWRzGkCHoWviloJwXKcY5zgBV1M+5aj3idXuwE0w7r57Uk16xaG+sYGo8zWkBCDDoiewfXAMcShjocX+JfJMGDmpQu2JNc1hOJxleEc=
  on:
    tags: true
    repo: lucidsushi/example_package_github_pixel3
    python: 2.7
