language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lucidsushi
  password:
    secure: TjSyMzP2aQuLw3k5/v2jbCyOmXG0GWLB54T57VZoLmql+fvRSPkVUOKXfhUGrTPLqXHy6mOuZzpEDzuIrP07yJHB2fb5Zp0vZNJaRoNevy6SxH9Znm8ptQja4mYPUmtwKo2UpzHtKIxAQnV6i1BpcVKqSa8KUYAy4jV+V7HHCsVNzN8rQW4oeOcBsiyP+fkQcZLo69OXybvIdl3wxOYJ+qPdgOUovpRm/+izg0goSS8398zhSsYJNWlkIfo9AOgIsibPwW92RzVN1wGkjuvmE2LNq+QcNhFgk2WjDHqL54zg6qQRL4KFWDD5dl2AGsC0ZU1gJ85Brm4bXxjAhZglxRaecwpQLJn10YUMThlCOnYjRiNlEgV/9N00xIDvlyGt7hdrXf9gaOX2hnGJRK1+VI459rUgzvP1rjyEzOZ7rycwIsr9I7WsaiTysRz5Y7zaTNIPp5NEo7SyDv+X74daY/yrZP2MZIHs/BWCIBHKmXFPTTEhVF0CvH43BlxzU50OzeIUnI/7hL+Jp3JJdmQXSQ0UOSfcME24V+YRYT1ZmKJc7Gr+LYvDDczmZA6PxIDoA4ejmIAqz2BwKQlPjANz9Z6H35keQY8MZKAmbfr/33kwzEYpxPVXYtLwz+ytnsvDsswwWnJaxEb5C2BAT6Fus6DnRr5nnCuN4jRjUpb6NMc=
  on:
    tags: true
    repo: lucidsushi/example_package_github_pixel3
    python: 2.7
